-- Itinerary events generated by Zo reference a real Google Place. Store its place_id so the
-- timeline / map / AR can later re-resolve the place (details, photo) on demand. Nullable: events
-- created by hand or by smart-import have no place_id. lat/lng already exist on trip_events.

alter table public.trip_events
  add column place_id text;
